name: CD Pipeline

on:
  push:
    branches: [ master ] # Only deploy when a push happens to the main branch

jobs:
  deploy:
    name: Deploy to AWS Elastic Beanstalk
    runs-on: ubuntu-latest
    environment: production # Sets up an environment in GitHub Actions UI

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven Wrapper executable
        run: chmod +x ./mvnw

      - name: Build with Maven (Skip Tests)
        run: ./mvnw clean package -DskipTests --no-transfer-progress # Package the JAR

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ncs-demo # Must match your EB App name
          environment_name: Ncs-demo-env # Find this in your EB dashboard
          version_label: github-${{ github.sha }} # Unique label for this deployment
          region: ap-southeast-2 # Change this to your AWS region (e.g., ap-southeast-1)
          deployment_package: target/demo-0.0.1-SNAPSHOT.jar # Path to the JAR we built
          wait_for_environment_recovery: 300 # Wait 300 seconds for deployment to finish